name: MLOps Training

on:
  push:
    branches: main
    paths-ignore:
    - 'data/**'
    -  '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Extract Model Training scripts from Notebook
      run: |
        pip3 install nbdev
        cp notebooks/mlops.ipynb code/processnotebook/
        cd code/processnotebook
        nbdev_build_lib
        cp -rf output/train.py ../train/train.py

    - name: 'Authenticate with Azure Container Registry'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Build and push container images for Kubeflow Pipeline'
      uses: azure/docker-login@v1
      with:
        login-server: kitchenregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build code/dataprep -t kitchenregistry.azurecr.io/prepdata:${{ github.sha }}
        docker tag kitchenregistry.azurecr.io/prepdata:${{ github.sha }} kitchenregistry.azurecr.io/prepdata:latest
        docker push kitchenregistry.azurecr.io/prepdata:${{ github.sha }}
        docker push kitchenregistry.azurecr.io/prepdata:latest
        docker build code/train -t kitchenregistry.azurecr.io/train:${{ github.sha }}
        docker tag kitchenregistry.azurecr.io/train:${{ github.sha }} kitchenregistry.azurecr.io/train:latest
        docker push kitchenregistry.azurecr.io/train:${{ github.sha }}
        docker push kitchenregistry.azurecr.io/train:latest
    
    - name: Kick off Kubeflow Pipelines Run
      uses: azure/CLI@v1
      with:
        azcliversion: 2.15.1
        inlineScript: |
          az aks get-credentials -g kubeflow-kitchen -n kitchencluster
          pip install kfp==1.1.1
          kfp run submit -e ${{ github.sha }} -r ${{ github.sha }} -p aec88455-03cf-4821-aa08-f628a926cd1b imagetag=${{ github.sha }}
          
