# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MLOps Training

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Build and push container images'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build src/prepdata -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/prepdata:${{ github.sha }}
        docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/prepdata:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/prepdata:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/prepdata:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/prepdata:latest
        docker build src/train -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/train:${{ github.sha }}
        docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/train:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/train:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/train:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/train:latest

